### PR TITLE
Support cross-compiling for MINGW64/MSYS2

### PR DESCRIPTION
**Pull request by sjoelund**
This adds support for a general MSYS2 installation such as when
cross-compiling from a Linux machine.

### CODE REVIEW

**Comment by sjoelund** [comment]
I think it should work fine on Windows machines still. It cross-compiles on my machine at least. Any comments?

**Comment by sjoelund** [comment]
Maybe... `MSYSROOT ?= $(shell cygpath $$OMDEV/tools/msys)`?

**Comment by lochel** [comment]
```bash
cp: kan inte ta status på '//mingw64/bin/libxml2-2.dll': No such file or directory
cp: kan inte ta status på '//mingw64/bin/libiconv-2.dll': No such file or directory
cp: kan inte ta status på '//mingw64/bin/zlib1.dll': No such file or directory
cp: kan inte ta status på '//mingw64/bin/libwinpthread-1.dll': No such file or directory
cp: kan inte ta status på '//mingw64/bin/libstdc++-6.dll': No such file or directory
cp: kan inte ta status på '//mingw64/bin/libgcc_s_seh-1.dll': No such file or directory
cp: kan inte ta status på '//mingw64/bin/liblzma-5.dll': No such file or directory
Makefile:22: receptet för målet ”all” misslyckades
```

**Comment by sjoelund** [comment]
Does it need to be \\ then?

**Comment by lochel** [comment]
Then I get
```bash
cp: kan inte ta status på '/c/OMDevtoolsmsys/mingw64/bin/libxml2-2.dll': No such file or directory
cp: kan inte ta status på '/c/OMDevtoolsmsys/mingw64/bin/libiconv-2.dll': No such file or directory
cp: kan inte ta status på '/c/OMDevtoolsmsys/mingw64/bin/zlib1.dll': No such file or directory
cp: kan inte ta status på '/c/OMDevtoolsmsys/mingw64/bin/libwinpthread-1.dll': No such file or directory
cp: kan inte ta status på '/c/OMDevtoolsmsys/mingw64/bin/libstdc++-6.dll': No such file or directory
cp: kan inte ta status på '/c/OMDevtoolsmsys/mingw64/bin/libgcc_s_seh-1.dll': No such file or directory
cp: kan inte ta status på '/c/OMDevtoolsmsys/mingw64/bin/liblzma-5.dll': No such file or directory
Makefile:22: receptet för målet ”all” misslyckades
```

**Comment by lochel** [comment]
Then I get...
```
cp: kan inte ta status på '//mingw64/bin/libxml2-2.dll': No such file or directory
cp: kan inte ta status på '//mingw64/bin/libiconv-2.dll': No such file or directory
cp: kan inte ta status på '//mingw64/bin/zlib1.dll': No such file or directory
cp: kan inte ta status på '//mingw64/bin/libwinpthread-1.dll': No such file or directory
cp: kan inte ta status på '//mingw64/bin/libstdc++-6.dll': No such file or directory
cp: kan inte ta status på '//mingw64/bin/libgcc_s_seh-1.dll': No such file or directory
cp: kan inte ta status på '//mingw64/bin/liblzma-5.dll': No such file or directory
Makefile:22: receptet för målet ”all” misslyckades
```

**Comment by sjoelund** [comment]
I wrote \\\\, but Github escapes it :)

**Comment by lochel** [comment]
I noticed that a bit too late :D

**Comment by sjoelund** [comment]
OK, what about the force pushed commit? (cygpath.exe doesn't work in wine like all cygwin executables)

**Comment by lochel** [comment]
```bash
g++  -std=c++11  -pipe -O2 -frtti -Wall -Wextra -fexceptions -DUNICODE -DINTERFACE_TYPES  WINDOWS64/main.o  WINDOWS64/Plugin/PluginImplementer.o  WINDOWS64/Communication/TLMClientComm.o  WINDOWS64/Communication/TLMCommUtil.o  WINDOWS64/Interfaces/TLMInterface.o  WINDOWS64/Interfaces/TLMInterfaceSignal.o  WINDOWS64/Interfaces/TLMInterfaceSignalInput.o  WINDOWS64/Interfaces/TLMInterfaceSignalOutput.o  WINDOWS64/Interfaces/TLMInterface1D.o  WINDOWS64/Interfaces/TLMInterface3D.o  WINDOWS64/Parameters/ComponentParameter.o  WINDOWS64/Logging/TLMErrorLog.o  WINDOWS64/Plugin/TLMPlugin.o  WINDOWS64/coordTransform.o  WINDOWS64/double3.o  WINDOWS64/double33.o  WINDOWS64/ErrorLog.o  WINDOWS64/double33s.o  WINDOWS64/dsyevq3.o  WINDOWS64/dsyevv3.o  WINDOWS64/dsyevc3.o  WINDOWS64/dsytrd3.o  WINDOWS64/Bstring.o  WINDOWS64/tostr.o  WINDOWS64/nvector_serial.o  WINDOWS64/sundials_math.o  WINDOWS64/sundials_nvector.o  WINDOWS64/sundials_direct.o  WINDOWS64/sundials_dense.o  WINDOWS64/cvode.o  WINDOWS64/cvode_dense.o  WINDOWS64/cvode_direct.o  WINDOWS64/cvode_io.o  WINDOWS64/ida.o  WINDOWS64/ida_dense.o  WINDOWS64/ida_direct.o  WINDOWS64/ida_io.o -o WINDOWS64/FMIWrapper.exe -L../../3rdParty/FMIL/install/mingw/lib -lfmilib -ldl -lboost_regex
C:/OMDev/tools/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ldl
C:/OMDev/tools/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lboost_regex
collect2.exe: error: ld returned 1 exit status
Makefile:119: receptet för målet ”default” misslyckades
```

**Comment by sjoelund** [comment]
What is your `uname -s` output?

**Comment by lochel** [comment]
```bash
$ uname -s
MINGW64_NT-10.0-WOW
```

**Comment by sjoelund** [comment]
OK, changed a bit due to annoying GNU make syntax for things that configure should have taken care of (conditionals)

**Pull request merged**
