### PR TITLE
Fix memory leaks

### PR DESCRIPTION
**Pull request by robbr48**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OMSimulator-PR/328//console). It may take a while, depending on the workload.
  - OpenModelica/OMTLMSimulator#72

**Comment by OpenModelica-Hudson** [comment]
**[ASan:](https://test.openmodelica.org/hudson/job/OMSimulator-PR/328/)** The test suite is unstable. :worried:

**Comment by OpenModelica-Hudson** [comment]
All tests were successful. :confetti_ball:

**Comment by lochel** [comment]
@robbr48 It would be nice to compile TLM simulator with ASan and debug symbols to see where the issues actually are. Can you forward and implement the flag `ASAN` inside the TLM simulator?

**Comment by robbr48** [comment]
I am not sure how to implement ASAN support manually. I guess  CMake takes care of the details for OMSimulator?

**Pull request closed without merging**
